/*
 * Abura Soba, 2025
 * 
 * Full Ray Tracing
 *
 * Gaussian Enclosing pass
 *
 * Compute shader
 */

#version 460
///////////////////////////////////////////////
#define MOGRenderAdaptiveKernelClamping 1 << 0
///////////////////////////////////////////////

#include "../base/define.glsl"

layout (local_size_x = 1) in;

layout(std430, binding = 0, set = 0) buffer IndirectBuffer {
	int x;
	int y;
	int z;
} indirectBuffer;

void main()
{	
    indirectBuffer.x = (indirectBuffer.x + TB_SIZE_X - 1) / TB_SIZE_X;
}
